workflow changes -- v1

diff --git a/.github/workflows/packer_build.yml b/.github/workflows/packer_build.yml
--- a/.github/workflows/packer_build.yml
+++ b/.github/workflows/packer_build.yml
@@ -93,7 +93,16 @@ jobs:
       
       - name: Copy AMI ID to Github Env
         run: |
-          AMI_ID=$(aws ec2 describe-images --owners 912764834865 --query 'Images | sort_by(@, &CreationDate) | [-1].ImageId'  --output text)
+          AMI_ID=$(aws ec2 describe-images --owners 912764834865 --query 'Images | sort_by(@, &CreationDate) | [-1].ImageId' --output text 2>&1)
+
+          # Check if the command was successful
+          if [ $? -eq 0 ]; then
+            echo "ami_id=$AMI_ID" >> "$GITHUB_ENV"
+          else
+            # Print the error message and exit with a non-zero status
+            echo "Error: $AMI_ID"
+            exit 1
+          fi
           echo "ami_id=$AMI_ID" >> "$GITHUB_ENV"
 
       - name: Fetch Launch Template ID
